version: '3'

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=task_db
    volumes:
      - pg-data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    build: ./tasksys
    command: celery -A tasksys worker -l INFO
    volumes:
      - ./tasksys/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_HOST=pg
      - DB_NAME=task_db
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - redis
      - web
      - pg

  celery-beat:
    build: ./tasksys
    command: celery -A tasksys beat -l INFO
    volumes:
      - ./tasksys/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_HOST=pg
      - DB_NAME=task_db
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - redis
      - pg
      - web

  web:
    build: ./tasksys
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tasksys:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - DB_HOST=pg
      - DB_NAME=task_db
      - DB_USER=user
      - DB_PASS=password
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
      - pg

volumes:
  pg-data: