version: '3'

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - pg-data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    build: ./tasksys
    command: celery -A tasksys worker -l INFO
    volumes:
      - ./tasksys/:/usr/src/app/
    env_file:
      - app.env
    depends_on:
      - redis
      - web
      - pg

  celery-beat:
    build: ./tasksys
    command: celery -A tasksys beat -l INFO
    volumes:
      - ./tasksys/:/usr/src/app/
    env_file:
      - app.env
    depends_on:
      - redis
      - pg
      - web

  web:
    build: ./tasksys
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tasksys:/usr/src/app
    ports:
      - '8000:8000'
    env_file:
      - app.env
    depends_on:
      - redis
      - pg

volumes:
  pg-data: