# Generated by Django 3.1 on 2022-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220417_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration of project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
