# Generated by Django 3.1 on 2022-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220417_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active_time',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='passive_time',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
